inactive-opacity = 1.0;
active-opacity = 1.0;

opacity-rule =  [
  "75:class_g = 'kitty' && focused",
  "70:class_g = 'kitty' && !focused"
];

backend = "glx";
#blur-background = true;
#blur-method = "dual_kawase";
#blur-strength = 5;

corner-radius = 10;

shadow = true;
shadow-radius = 7;
shadow-opacity = 0.3;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
