[colors]
background = #282828
foreground = #ebdbb2
yellow     = #b57614
red        = #cc241d
brown      = #3c3836

override-redirect = true

[bar/main]
offset-y = 10
offset-x = 1%
width = 100%
border-size = 1
#border-color = ${colors.yellow}
radius = 6
height = 27
position = top
background = ${colors.background}
foreground = ${colors.foreground}

font-0 = Terminus:pixelsize=13;2
font-1 = Mononoki Nerd Font:pixelsize=13;2

padding-left = 1
padding-right = 1
module-margin = 1

modules-left = i3
modules-center = date
modules-right = cpu temperature memory network

separator = |
separator-foreground = ${colors.yellow}

[module/i3]
type = internal/i3
format = <label-state>
label-focused = %index%
label-focused-foreground = ${colors.yellow}
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-foreground = ${colors.brown}
label-unfocused-padding = 2

[module/cpu]
type = internal/cpu
interval = 2
format = CPU: <label>
label = %percentage%%

[module/temperature]
type = internal/temperature
hwmon-path = /sys/class/hwmon/hwmon2/temp1_input
interval = 2
format = TEMP: <label>
label = %temperature-c%

[module/memory]
type = internal/memory
interval = 2
format = RAM: <label>
label = %mb_used%/%mb_total%

[module/network]
type = internal/network
interface = wlan0
interval = 3
format-connected = NET: <label-connected>
label-connected = %local_ip%
format-disconnected = NET: down

[module/date]
type = internal/date
interval = 1
date = %a %d %b
time = %H:%M
format = <label>
label = %date% %time%
